name: 'execute gradlew'
description: 'execute gradlew command'
inputs:
  task:
    description: execute task
    required: false
    default: shadowjar
  working-directory:
    description: 'gradlew command execute directory'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.task }}
    - ${{ inputs.working-directory }}







